---
- hosts : localhost
  user: root
  tasks:
     - name: create API key
       uri:
          url="http://172.27.59.169:8080/v1/projects/1a5/apikeys"
          return_content=yes
          method=POST
          status_code=200
          HEADER_Content-Type="application/json"
       register: project_id
       ignore_errors: True
 

     - debug: var={{ project_id.json.publicValue }}

     - debug: var={{ project_id.json.secretValue }}

     - debug: var={{ project_id.json.id }}

     - name: export variables
       shell: echo RANCHER_ACCESS_KEY={{ project_id.json.publicValue }}
     
     - name: export variables
       shell: export RANCHER_SECRET_KEY={{ project_id.json.secretValue }}     

    # - local_action: copy content={{ project_id.json.secretValue }} dest=/compose/test

     - local_action: shell echo "RANCHER_SECRET_KEY={{ project_id.json.secretValue }}" > /root/testing

     - name: create API key
       uri:
          url="http://172.27.59.169:8080/v1/projects/1a5/apikeys/{{ project_id.json.id }}"
          return_content=yes
          method=GET
          status_code=200
          HEADER_Content-Type="application/json"
       register: secret_value
       ignore_errors: True

     - debug: var=secret_value
  

    # - name: Dactivate API key 
    #   uri:
    #      url="http://172.27.59.169:8080/v1/projects/1a5/apikeys/{{ project_id.json.id }}?action=deactivate"
    #      return_content=yes
    #      method=POST
    #      status_code=200
    #      HEADER_Content-Type="application/json"
    #   ignore_errors: True
       
    # - name: Delete API key
    #   uri:
    #      url="http://172.27.59.169:8080/v1/projects/1a5/apikeys/{{ project_id.json.id }}"
    #      return_content=yes
    #      method=DELETE
    #      status_code=200
    #      HEADER_Content-Type="application/json"
    #   ignore_errors: True
         



