---
- name: Pull and run the Rancher/server contianer
  docker:
      name: "{{ rancher_name }}"
      image: rancher/server:v0.47.0
      restart_policy: always
      ports: 
        - "{{ rancher_port }}:8080"
      volumes:
        - /rancher/data:/var/lib/mysql

- name: Wait for the Rancher server to start
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ ansible_default_ipv4.address }}:{{ rancher_port }}"


- name: install rancher-compose
  copy: src=rancher-compose dest=/usr/bin/ mode=u+rwx
