---
# defaults file for rancher-compose
rancher_name: 'rancher_server'
rancher_port: 8080


<<<<<<< HEAD
RANCHER_URL: 'http://172.27.59.169:8080/'
=======
RANCHER_URL: 'http://172.27.59.136:8080/'
>>>>>>> ca3391fa81c96de7c4ca628e0834fb1ae66684c6

RANCHER_ACCESS_KEY: '769A7E7736A2908ECAFD'

RANCHER_SECRET_KEY: 'xGuK8SPkyp2WXTFef5zbVpGnihKZ9amw8UaS9SL6'
